name: Deploy MERN App to EC2

on:
  push:
    branches:
      - main  # or 'production' or any branch you merge into for deployment

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/your-mern-app
          git pull origin main
          cd backend
          npm install
          pm2 restart backend || pm2 start index.js --name backend
          cd ../frontend
          npm install
          npm run build

