name: Build and Push Backend & Frontend Docker Images

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_EMAIL }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest


      - name: Build and push frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./Client_React
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
  deploy-backend:
    needs: build-and-push
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest 
      - name: Delete old container
        run: docker rm -f nodejs-app-container  || true
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name nodejs-app-container ${{ secrets.DOCKER_USERNAME }}/backend:latest

  deploy-reactjs:
    needs: build-and-push
    runs-on: [self-hosted, Client_React-runner]
    steps:
      - name: Pull image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
      - name: Delete old container
        run: docker rm -f reactjs-app-container || true
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactjs-app-container ${{ secrets.DOCKER_USERNAME }}/frontend:latest